### ISSUE TITLE
Wrong result for http://ppr.cs.dal.ca:3002/n3/editor/s/fBdRtr3x with eye

### ISSUE THREAD

**Issue by josd** [william-vw/n3-editor-js#4]
The result for http://ppr.cs.dal.ca:3002/n3/editor/s/fBdRtr3x with eye is wrong.
The [latest version of eye](https://github.com/josd/eye/releases/tag/v22.0117.1432) gives correct results.

**Comment by william-vw** [comment]
Ok I updated the editor - feel free to re-open the issue if there's still problems
